### ISSUE TITLE
Issue when logging out

### ISSUE THREAD

**Issue by Kaggypants** [RokasKil/TitleEdit#1]
I'm experiencing an issue with TitleEdit when I log out. Essentially, some of the in-game assets are being displayed on the login screen while the title edit screen is also resized.

Please see the screenshot below. You can see that my FC's company workshop is currently being displayed in the bottom, lower right section, and right side of the screen. This is where I had just logged out. 

![bug](https://github.com/user-attachments/assets/d86da50e-9eee-4506-be40-b2a3ea269b0c)

**Comment by RokasKil** [comment]
Hi, how did you get here? Are you using the TitleEdit on plugin installer or did you clone this repo and build it yourself cause the plugin here isn't released yet. Are you using any other plugins that might affect the game's lobby in any way?

**Comment by Kaggypants** [comment]
Using Google. The other TitleEdit repository does not have a way to open issues. Other plugins that might affect TitleEdit:

**SimpleTweaks**:
1. Data Centre on Title Screen is checked
2. Disable Title Screen Movie is checked
3. Remember Title Sorting is checked

**No Kill Plugin**

**Ultrawide Cutscenes**

Also have Reshade installed.

**Comment by Kaggypants** [comment]
Closing this. If anyone else has the same issue, it's a result of setting Reshade DLSSQualityLevels fields to something other than your native resolution. i.e., my native resolution is 3440x1440 but Reshade was set to 1920x1080
