### ISSUE TITLE
Issue with creating a retainer

### ISSUE THREAD

**Issue by panthea22** [RokasKil/TitleEdit#2]
For some reason Title edit is causing the camera in the retainer customization to go haywire. It's half underground for three of them, with no character model to be seen. And the other 2 (aether and inn room) are just black screens. I turned off title edit, relogged and there was no more issue. Once I turned it back on it happened again. I changed the camera to static and its still happening.
![Screenshot 2024-10-18 171510](https://github.com/user-attachments/assets/67f0c57e-dfef-4679-8cff-c04de9cf51bd)
![Screenshot 2024-10-18 171534](https://github.com/user-attachments/assets/f52a7462-e748-4e7b-8315-3bdf52fccdab)
![Screenshot 2024-10-18 171556](https://github.com/user-attachments/assets/09afe69e-89d6-4cac-a358-4435d8172b34)

**Comment by RokasKil** [comment]
Hi, thanks for the report! I can reproduce this so will be fixed soonish.

**Comment by RokasKil** [comment]
Pushed out a fix
