### ISSUE TITLE
[Bug] Furniture from housing-based character selection preset remains on vanilla title screens

### ISSUE THREAD

**Issue by Lapidearum** [RokasKil/TitleEdit#5]
Using a character selection preset that includes custom housing items and then returning to any of the vanilla title screen presets aside from Dawntrail results in the housing items being left on the screen.

Attached for reference are pictures of my own preset, followed by the ARR, Heavensward (Stormblood and Shadowbringers are identical in placement) and Endwalker screens as they appear after loading it.

![2024-12-10 17-59-34 EG11 - 00 - Shadowbringers Gameplay](https://github.com/user-attachments/assets/4f218314-63d4-4d92-a0db-4c9a8ec518a2)

![2024-12-10 17-43-57 EG11 - 00 - Shadowbringers Gameplay](https://github.com/user-attachments/assets/17821944-141c-43ba-84ca-43b52dcd3371)

![2024-12-10 17-46-36 EG11 - 00 - Shadowbringers Gameplay](https://github.com/user-attachments/assets/3d143081-f9be-4364-9f90-95fa9f2d82dc)

![2024-12-10 17-46-16 EG11 - 00 - Shadowbringers Gameplay](https://github.com/user-attachments/assets/3baf56e6-7bce-40a2-a791-9f6d941e21f9)

**Comment by RokasKil** [comment]
Thanks for the report, I'll get that fixed
